spring:
  data:
    mongodb:
      database: beishan
      username: 
      password: 
      host: 

pivotviewer:
  deepzoom:
    root-path: /var/diseasePest/beishan

i18n:
  message:
    base-names:
      - i18n/messages
      - i18n/messages-beishan

app:
  name: beishan
  alias: 互助北山

external:
  link:
    plant: 
    animal: 
    gis: 
    visualization:
    insect:
