spring:
  data:
    mongodb:
      database: qilian
      username: 
      password: 
      host: 

pivotviewer:
  deepzoom:
    root-path: /var/diseasePest/qilian

i18n:
  message:
    base-names:
      - i18n/messages
      - i18n/messages-qilian

app:
  name: qilian
  alias: 祁连

external:
  link:
    plant: 
    animal: 
    gis: 
    visualization:
    insect:
