spring:
  data:
    mongodb:
      database: beishan_test
      host: 172.18.0.2

pivotviewer:
  deepzoom:
    root-path: /var/diseasePest/beishan

i18n:
  message:
    base-names:
      - i18n/messages
      - i18n/messages-beishan
server:
  context-path: /beishan-1.0
  port: 8444

app:
  name: beishan
  alias: 互助北山

external:
  link:
    plant: 
    animal: 
    gis: 
    visualization:
    insect:
